version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app-container
    ports:
      - "5001:5000"  # Mapping host port 5001 to container port 5000
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py
      MYSQL_HOST: mysql
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    depends_on:
      - mysql
    volumes:
      - .:/Application
    command: ["sh", "-c", "/wait-for-it.sh mysql:3306 -- gunicorn -b 0.0.0.0:${PORT} main:app"]  # Gunicorn with ${PORT}

  mysql:
    image: mysql:8.0.32
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./setupDatabase.sql:/docker-entrypoint-initdb.d/setupDatabase.sql
    command: --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
